import React from 'react';

const FAQ: React.FC = () => {
  return (
    <div className="max-w-3xl mx-auto animate-fade-in pb-20">
      <h2 className="text-4xl font-cinzel text-white mb-2">F.A.Q.</h2>
      <p className="text-neutral-400 font-inter mb-12">Frequently Asked Questions regarding system operations.</p>

      <div className="space-y-6">
        
        <div className="bg-[#0A0A0A] border border-neutral-800 p-6 rounded hover:border-[#FFD700] transition-colors group">
          <h3 className="text-lg font-cinzel text-white mb-2 group-hover:text-[#FFD700]">Is OBSCURA.AI free to use?</h3>
          <p className="text-neutral-400 text-sm leading-relaxed">
            The application interface is free to access. However, because it utilizes Google's advanced Gemini 3 Pro models, it requires a valid API Key. In this demo environment, a key is often pre-configured, but for production use, you may need your own key from Google AI Studio.
          </p>
        </div>

        <div className="bg-[#0A0A0A] border border-neutral-800 p-6 rounded hover:border-[#FFD700] transition-colors group">
          <h3 className="text-lg font-cinzel text-white mb-2 group-hover:text-[#FFD700]">Where is my data stored?</h3>
          <p className="text-neutral-400 text-sm leading-relaxed">
            OBSCURA.AI operates on a <strong>Local-First</strong> architecture. Your API keys, chat history, and generated results are stored locally in your browser's <code>localStorage</code>. No personal data is sent to our servers. Data sent to the AI model is processed by Google subject to their privacy policy.
          </p>
        </div>

        <div className="bg-[#0A0A0A] border border-neutral-800 p-6 rounded hover:border-[#FFD700] transition-colors group">
          <h3 className="text-lg font-cinzel text-white mb-2 group-hover:text-[#FFD700]">Why does the Storyboard export look different?</h3>
          <p className="text-neutral-400 text-sm leading-relaxed">
            The app interface uses a "Dark Mode" cinematic aesthetic. However, the Storyboard exports (PDF and JPG) are rendered in a high-contrast "Production White" style. This is intentional to ensure they are legible when printed or shared in professional production binders.
          </p>
        </div>

        <div className="bg-[#0A0A0A] border border-neutral-800 p-6 rounded hover:border-[#FFD700] transition-colors group">
          <h3 className="text-lg font-cinzel text-white mb-2 group-hover:text-[#FFD700]">Can I use the images commercially?</h3>
          <p className="text-neutral-400 text-sm leading-relaxed">
            The SVG sketches generated by the Storyboard tool are created by AI. Currently, AI-generated artwork laws vary by region. Generally, you can use them for internal pre-production, pitch decks, and planning without issue.
          </p>
        </div>

        <div className="bg-[#0A0A0A] border border-neutral-800 p-6 rounded hover:border-[#FFD700] transition-colors group">
          <h3 className="text-lg font-cinzel text-white mb-2 group-hover:text-[#FFD700]">My API Key isn't working?</h3>
          <p className="text-neutral-400 text-sm leading-relaxed">
            Ensure your API key has access to the <code>gemini-3-pro-preview</code> model. You can verify your key status at <a href="https://aistudio.google.com/" target="_blank" className="text-[#FFD700] underline">Google AI Studio</a>. If using Guest Mode, try clearing your browser cache and signing in again.
          </p>
        </div>

      </div>
    </div>
  );
};

export default FAQ;